#!/usr/bin/env bash
# Git hooks 설치 — commit-msg에서 Co-Authored-By 자동 제거.
#
# Usage: bash scripts/install-hooks.sh
#
# AI assistant (Claude·Copilot 등)가 commit message에 본인을 contributor로 추가하는 패턴 차단.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOK_DIR="$REPO_ROOT/.git/hooks"

if [ ! -d "$HOOK_DIR" ]; then
  echo "✗ .git/hooks not found. Run inside a git repo."
  exit 1
fi

cat > "$HOOK_DIR/commit-msg" << 'EOF'
#!/usr/bin/env bash
# AI contributor 제거 — Co-Authored-By 라인 자동 삭제.
# 정책: 사람 contributor만 git history에 기록.
MSG_FILE="$1"
[ -f "$MSG_FILE" ] || exit 0

# Co-Authored-By: ... + "🤖 Generated by Claude Code" + 유사 패턴 제거
sed -i \
  -e '/^Co-Authored-By:/d' \
  -e '/^Co-authored-by:/d' \
  -e '/🤖 Generated with .*Claude/d' \
  -e '/Generated by Claude Code/d' \
  "$MSG_FILE"

# trailing 빈 라인 정리
sed -i -e :a -e '/^$/{$d;N;ba' -e '}' "$MSG_FILE"
exit 0
EOF
chmod +x "$HOOK_DIR/commit-msg"
echo "✓ Installed: .git/hooks/commit-msg (Co-Authored-By 자동 제거)"
